modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "newplayerprotector"
version = "${version}"
displayName = "NewPlayerProtector"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''